name: EasyLM
channels:
    - defaults
    - nvidia
    - conda-forge
dependencies:
    - python=3.8
    - pip
    - numpy
    - scipy
    - numba
    - h5py
    - matplotlib
    - scikit-learn
    - jupyter
    - tqdm
    - protobuf=3.20.*
    - pytorch=1.12.1
    - jax=0.3.16
    - jaxlib=0.3.15=*cuda*
    - cudatoolkit=11.3
    - cuda-nvcc=11.3
    - cudnn
    - flask
    - pip:
        - flax==0.6.0
        - optax==0.1.3
        - distrax==0.1.2
        - transformers==4.24.0
        - datasets==2.7.0
        - einops
        - tensorflow==2.8.0
        - dill
        - seaborn
        - absl-py
        - gtimer
        - joblib
        - wandb==0.13.5
        - ml_collections
        - gcsfs==2022.11.0
        - requests
        - jupyter_http_over_ws
